name       : libopenshot
version    : 0.2.2
release    : 11
source     :
    - https://github.com/OpenShot/libopenshot/archive/v0.2.2.tar.gz : 3f92d42b9fdb66e62429a076678b1feae7de06751efc4217347a78282e86f0cc
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : A high quality, open-source video editing, animation, and playback library for C++, Python, and Ruby
description: |
    libopenshot is an open-source, cross-platform C++ library dedicated to delivering high quality video editing, animation, and playback solutions to the world. This is the same library which powers OpenShot Video Editor (version 2.0+) and it could power your next video editing application!
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ImageMagick)
    - pkgconfig(jsoncpp)
    - pkgconfig(libavcodec)
    - pkgconfig(libzmq)
    - pkgconfig(python3)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(UnitTest++)
    - pkgconfig(x264)
    - cppzmq-devel
    - doxygen
    - libopenshot-audio-devel
    - swig
setup      : |
    # Fix build with imagemagick7
    %patch -p1 < $pkgfiles/imagemagick7.patch
    # Build fails with ruby enabled, reenable at a later date.
    %cmake -DUSE_SYSTEM_JSONCPP=ON -DENABLE_RUBY=OFF -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test || :
