name       : libopenshot
version    : 0.1.6
release    : 2
source     :
    - https://launchpad.net/libopenshot/0.1/0.1.6/+download/libopenshot-0.1.6.tar.gz : 3a5caf0e3b0fdb4137303e434b2bd525445da6867e8a16a0584bd3410bddbd93
license    : GPL-3.0
component  : multimedia.library
summary    : A high quality, open-source video editing, animation, and playback library for C++, Python, and Ruby.
description: |
    libopenshot is an open-source, cross-platform C++ library dedicated to delivering high quality video editing, animation, and playback solutions to the world. This is the same library which powers OpenShot Video Editor (version 2.0+) and it could power your next video editing application!
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ImageMagick)
    - pkgconfig(jsoncpp)
    - pkgconfig(libavcodec)
    - pkgconfig(libzmq)
    - pkgconfig(python-3.5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(UnitTest++)
    - pkgconfig(x264)
    - cppzmq
    - doxygen
    - libopenshot-audio-devel
    - swig
setup      : |
    # Build fails with ruby enabled, reenable at a later date.
    %cmake -DUSE_SYSTEM_JSONCPP=ON -DENABLE_RUBY=OFF
build      : |
    %make
install    : |
    %make_install
