name       : libopenshot
version    : 0.2.3
release    : 15
source     :
    - https://github.com/OpenShot/libopenshot/archive/v0.2.3.tar.gz : 8536b0a790b0d98ed4c3b10e11d1b34ae68ccbc710887e3703a5143d95598746
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : A high quality, open-source video editing, animation, and playback library for C++ and Python
description: |
    libopenshot is an open-source, cross-platform C++ library dedicated to delivering high quality video editing, animation, and playback solutions to the world. This is the same library which powers OpenShot Video Editor (version 2.0+) and it could power your next video editing application!
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(UnitTest++)
    - pkgconfig(gl)
    - pkgconfig(jsoncpp)
    - pkgconfig(libavcodec)
    - pkgconfig(libzmq)
    - pkgconfig(python3)
    - pkgconfig(x264)
    - cppzmq-devel
    - doxygen
    - libopenshot-audio-devel
    - swig
setup      : |
    %patch -p1 < $pkgfiles/imagemagick7.patch
    %patch -p1 < $pkgfiles/integrate-juce-5-library.patch
    # Build fails with ruby enabled, reenable at a later date.
    %cmake -DUSE_SYSTEM_JSONCPP=ON -DENABLE_RUBY=OFF -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test || :
